import { describe, expect, it } from 'vitest';
import { BacklogIntakeGateway } from './backlogIntake';
import { applyGroomingDecision } from './backlogGrooming';
import { founderInboxCandidate } from './productBacklog';

describe('PM backlog grooming', () => {
  it('promotes only with an explicit PM-approved ProductBacklogItem and never creates execution', async () => { const source = await new BacklogIntakeGateway(`/tmp/groom-${Date.now()}`).submit({ project_id: 'macro-os', source_type: 'FOUNDER', source_id: 'idea-1', created_by: 'founder', observation: 'Evidence is hard to inspect', problem_signal: 'Research trust is reduced', affected_product_area: 'evidence', evidence_ids: ['E-1'], evidence_quality: 'SUFFICIENT', severity_signal: 'HIGH', confidence_signal: .9 }); const item = { ...founderInboxCandidate({ title: 'Evidence UX' }), backlog_id: 'BL-1', problem_statement: 'Evidence is hard to inspect', expected_product_value: 'Higher trust', expected_change: 'Show provenance', acceptance_criteria: ['source visible'], pm_review_status: 'APPROVED', status: 'READY', priority: 'P1', evidence_ids: ['E-1'], implementation_task_ids: [], evaluation_ids: [], learning_ids: [] } as any; const result = applyGroomingDecision(source.candidate, { action: 'PROMOTE', candidate_id: source.candidate.candidate_id, decided_by: 'pm', reason: 'aligned', product_backlog_item: item }); expect(result.candidate.status).toBe('PROMOTED'); expect(result.backlog_item?.backlog_id).toBe('BL-1'); });
  it('merges evidence and keeps one backlog identity', async () => { const source = await new BacklogIntakeGateway(`/tmp/groom-${Date.now()}`).submit({ project_id: 'macro-os', source_type: 'QA', source_id: 'qa-1', created_by: 'qa', observation: 'same issue', problem_signal: 'same problem', affected_product_area: 'evidence', evidence_ids: ['E-2'], evidence_quality: 'SUFFICIENT', severity_signal: 'MEDIUM', confidence_signal: .8 }); const existing = { backlog_id: 'BL-1', evidence_ids: ['E-1'], updated_at: '' } as any; const result = applyGroomingDecision(source.candidate, { action: 'MERGE', candidate_id: source.candidate.candidate_id, decided_by: 'pm', reason: 'same root problem', backlog_id: 'BL-1' }, existing); expect(result.candidate.status).toBe('MERGED'); expect(result.backlog_item?.evidence_ids).toEqual(['E-1', 'E-2']); });
  it('does not let a candidate become executable through grooming', async () => { const source = await new BacklogIntakeGateway(`/tmp/groom-${Date.now()}`).submit({ project_id: 'macro-os', source_type: 'ENGINEERING', source_id: 'eng-1', created_by: 'engineer', observation: 'slow path', problem_signal: 'research is slow', affected_product_area: 'performance', evidence_ids: ['E-3'], evidence_quality: 'REQUIRES_MORE_EVIDENCE', severity_signal: 'LOW', confidence_signal: .5 }); const result = applyGroomingDecision(source.candidate, { action: 'HOLD_FOR_EVIDENCE', candidate_id: source.candidate.candidate_id, decided_by: 'pm', reason: 'need profiling' }); expect(result.candidate.status).toBe('HOLD_FOR_EVIDENCE'); expect(result.backlog_item).toBeUndefined(); });
});
