import { appendFile, mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import type { CeoReview } from './ceoReviewLedger';

export interface Escalation { escalation_id: string; project_id: string; trigger: 'READY_FOR_RESCORE' | 'SCORE_DRIFT'; target_id: string; severity: 'P0' | 'P1'; owner_role: 'ceo' | 'pm'; status: 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED'; reason: string; created_at: string; }
export class EscalationLedger {
  private readonly file: string;
  constructor(private readonly rootDir: string) { this.file = path.join(rootDir, 'escalations.jsonl'); }
  async records(projectId?: string): Promise<Escalation[]> { try { const latest = new Map<string, Escalation>(); for (const line of (await readFile(this.file, 'utf8')).split('\n').filter(Boolean)) { const row = JSON.parse(line) as Escalation; latest.set(row.escalation_id, row); } const rows = [...latest.values()]; return projectId ? rows.filter((row) => row.project_id === projectId) : rows; } catch (error: unknown) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return []; throw error; } }
  async create(input: Omit<Escalation, 'created_at'>): Promise<Escalation> { const existing = (await this.records(input.project_id)).find((row) => row.escalation_id === input.escalation_id); if (existing) return existing; await mkdir(this.rootDir, { recursive: true }); const row = { ...input, created_at: new Date().toISOString() }; await appendFile(this.file, `${JSON.stringify(row)}\n`, 'utf8'); return row; }
  async transition(id: string, status: 'ACKNOWLEDGED' | 'RESOLVED', actor: 'ceo' | 'pm', evidenceIds: string[] = []): Promise<Escalation> { const item = (await this.records()).find((row) => row.escalation_id === id); if (!item) throw new Error(`escalation not found: ${id}`); if (item.status === 'RESOLVED') throw new Error('escalation is already resolved'); if (status === 'ACKNOWLEDGED' && item.status !== 'OPEN') throw new Error(`escalation is not open: ${item.status}`); if (status === 'RESOLVED' && item.status !== 'ACKNOWLEDGED') throw new Error(`escalation must be acknowledged first: ${item.status}`); if (actor !== item.owner_role) throw new Error(`escalation owned by ${item.owner_role}`); if (status === 'RESOLVED' && !evidenceIds.length) throw new Error('resolution evidence is required'); const next = { ...item, status, reason: evidenceIds.length ? `${item.reason}; resolution evidence=${evidenceIds.join(',')}` : item.reason, created_at: new Date().toISOString() }; await mkdir(this.rootDir, { recursive: true }); await appendFile(this.file, `${JSON.stringify(next)}\n`, 'utf8'); return next; }
}
export async function createCeoEscalations(review: CeoReview, ledger: EscalationLedger): Promise<Escalation[]> { const created: Escalation[] = []; for (const ideaId of review.ready_for_rescore_ideas) created.push(await ledger.create({ escalation_id: `ESC-RESCORE-${ideaId}`, project_id: review.project_id, trigger: 'READY_FOR_RESCORE', target_id: ideaId, severity: 'P1', owner_role: 'pm', status: 'OPEN', reason: 'research quorum is ready for evidence-aware re-score' })); for (const change of review.score_changes.filter((item) => item.action === 'REDECIDE')) created.push(await ledger.create({ escalation_id: `ESC-DRIFT-${change.idea_id}-${review.period}`, project_id: review.project_id, trigger: 'SCORE_DRIFT', target_id: change.idea_id, severity: 'P1', owner_role: 'ceo', status: 'OPEN', reason: `opportunity score changed from ${change.previous} to ${change.current}` })); return created; }
