import{mkdtemp,mkdir,writeFile,readFile,readdir}from'node:fs/promises';import os from'node:os';import path from'node:path';import{spawn}from'node:child_process';import{createHash}from'node:crypto';import{createRequire}from'node:module';import{RoleWorkQueue}from'../../../server/aiCompany/roleWorkQueue.ts';import{RoleHandoffLedger}from'../../../server/aiCompany/roleHandoffLedger.ts';
const sources=['scripts/ai-company-role-dispatch.mjs','server/aiCompany/roleWorkQueue.ts','server/aiCompany/cliAttemptDispatch.test.ts'];const hash=(x:any)=>createHash('sha256').update(x).digest('hex');async function hashes(){return Object.fromEntries(await Promise.all(sources.map(async f=>[f,hash(await readFile(f))])));}const before=await hashes();const results:any[]=[];
for(const mode of ['success-marker','stop-after-claim-ack']){
const root=await mkdtemp(path.join(os.tmpdir(),'independent-cli-issuance-'));const runtime=path.join(root,'.ai-company/runtime/projects/isolated');const queue=new RoleWorkQueue(runtime);const item=await queue.create({project_id:'isolated',backlog_id:'B',title:'Unit only; actual outcome unknown',role:'ux-research'});await new RoleHandoffLedger(runtime).record({project_id:'isolated',work_id:item.work_id,from_role:'ceo',to_role:item.role,actor:'unit',objective:item.title,context:['unit'],evidence_ids:['unit'],acceptance_criteria:['unit']});const bin=path.join(root,'stub-bin');await mkdir(bin);await mkdir(path.join(root,'.ai-company/reports'),{recursive:true});await writeFile(path.join(bin,'codex'),`#!${process.execPath}
const fs=require('node:fs');const row=fs.readFileSync('.ai-company/runtime/projects/isolated/role-work-queue.jsonl','utf8').trim().split('\\n').map(JSON.parse).at(-1);fs.writeFileSync('stub-call.json',JSON.stringify({state:row.state,attempt_id:row.attempt_id,marker:row.provider_dispatch,handleInArgs:process.argv.join(' ').includes('attempt_authority')}));const id=process.argv.at(-1).match(/RECEIPT EVIDENCE ID: ([A-Za-z0-9_:-]+)/)[1];const text='ROLE_RESEARCH_RESULT_JSON '+JSON.stringify({research_question:'unit',source_reference:id,finding:'unit stub only',confidence:.2})+'\\nROLE_WORK_COMPLETE';console.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text}}));console.log(JSON.stringify({type:'turn.completed',usage:{input_tokens:1,output_tokens:1}}));
`,{mode:0o700});const child=spawn(process.execPath,['--import',createRequire(import.meta.url).resolve('tsx'),path.join(process.cwd(),'scripts/ai-company-role-dispatch.mjs'),'--role',item.role,'--work-id',item.work_id,'--project-id','isolated','--runner','codex','--model','unit-stub','--control-root',root],{cwd:root,env:{...process.env,PATH:bin+path.delimiter+process.env.PATH,AI_COMPANY_REQUIRE_WORKTREE:'false'},stdio:['ignore','pipe','pipe','ipc']});let stderr='';child.stderr!.on('data',x=>stderr+=String(x));child.stdout!.resume();const exit=new Promise(resolve=>child.on('close',resolve));const timer=setTimeout(()=>child.kill('SIGKILL'),10000);let stoppedHash;
if(mode==='stop-after-claim-ack'){await new Promise<void>(resolve=>child.once('message',()=>{process.kill(child.pid!,'SIGSTOP');resolve();}));try{const selected=(await queue.records())[0];await queue.block(item.work_id,'Independent stop before provider',selected);stoppedHash=hash(await readFile(path.join(runtime,'role-work-queue.jsonl')));}finally{process.kill(child.pid!,'SIGCONT');}}
const code=await exit;clearTimeout(timer);const names=await readdir(root);const final=(await queue.records())[0];results.push({mode,root,code,stderr,stubCalled:names.includes('stub-call.json'),stubObservation:names.includes('stub-call.json')?JSON.parse(await readFile(path.join(root,'stub-call.json'),'utf8')):null,state:final.state,stoppedHistoryUnchanged:stoppedHash?stoppedHash===hash(await readFile(path.join(runtime,'role-work-queue.jsonl'))):undefined});}
const after=await hashes();await writeFile('docs/successor-takeover/evidence/cli-issuance-independent-result.json',JSON.stringify({observedAt:new Date().toISOString(),sourceHashesBefore:before,sourceHashesAfter:after,sourceStable:JSON.stringify(before)===JSON.stringify(after),realProviders:0,networkCalls:0,canonicalMutations:false,results},null,2));
