import{mkdtemp,readFile,writeFile,mkdir,symlink,unlink,appendFile}from'node:fs/promises';import os from'node:os';import path from'node:path';import{createHash}from'node:crypto';import{RoleWorkQueue}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkQueue.ts';import{InMemoryEvidenceResolver}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/evidenceResolver.ts';
const outputs:any[]=[];const spec={project_id:'fixture',backlog_id:'B',title:'temp only',role:'user-persona' as const,run_id:'R',namespace:'N'};const root=()=>mkdtemp(path.join(os.tmpdir(),'independent-gate-edge-'));
{
 const dir=await root();const q=new RoleWorkQueue(dir);const old=process.env.AI_COMPANY_FORENSIC_RUN_ID;process.env.AI_COMPANY_FORENSIC_RUN_ID='isolated';await mkdir(path.join(dir,'forensic-write-provenance.jsonl'));
 let error='';try{await q.create(spec)}catch(e){error=(e as Error).message}finally{if(old===undefined)delete process.env.AI_COMPANY_FORENSIC_RUN_ID;else process.env.AI_COMPANY_FORENSIC_RUN_ID=old}
 outputs.push({kind:'createProvenanceError',error,committedRows:(await q.records()).length,dir});
}
{
 const dir=await root();const q=new RoleWorkQueue(dir);const item=await q.create(spec);await appendFile(path.join(dir,'role-work-queue.jsonl'),JSON.stringify({...item,queue_revision:Number.MAX_SAFE_INTEGER})+'\n');const before=await readFile(path.join(dir,'role-work-queue.jsonl'));let updateError='';try{await q.claim(item.work_id,'fixture')}catch(e){updateError=(e as Error).message}let subsequentReadError='';try{await q.records()}catch(e){subsequentReadError=(e as Error).message}outputs.push({kind:'revisionOverflow',updateError,subsequentReadError,bytesUnchanged:before.equals(await readFile(path.join(dir,'role-work-queue.jsonl'))),dir});
}
{
 const base=await root();const a=path.join(base,'A'),b=path.join(base,'B'),alias=path.join(base,'alias');await mkdir(a);await mkdir(b);await symlink(a,alias);const resolver=new InMemoryEvidenceResolver();const q=new RoleWorkQueue(alias,resolver);const item=await q.create(spec);await q.claim(item.work_id,'fixture');await q.submitForReview(item.work_id);resolver.register({...resolver.createEvidence({evidence_id:'E',namespace:'N',run_id:'R',produced_by_role:'user-persona',content:'isolated'}),work_id:item.work_id,source_artifact:'/tmp/fixture'});await writeFile(path.join(b,'role-work-queue.jsonl'),await readFile(path.join(a,'role-work-queue.jsonl')));
 let entered!:()=>void,resume!:()=>void;const barrier=new Promise<void>(r=>entered=r),release=new Promise<void>(r=>resume=r);const realResolve=resolver.resolve.bind(resolver);resolver.resolve=(async(id:string)=>{entered();await release;return realResolve(id)}) as any;
 const pending=q.complete(item.work_id,['E'],{research_question:'fixture',source_reference:'E',finding:'fixture',confidence:.5});await barrier;await unlink(alias);await symlink(b,alias);resume();const done=await pending;outputs.push({kind:'rootRetarget',completion:done.state,rootAState:(await new RoleWorkQueue(a).records())[0].state,rootBState:(await new RoleWorkQueue(b).records())[0].state,base});
}
for(const f of ['server/aiCompany/queueMutationGate.ts','server/aiCompany/roleWorkQueue.ts','server/aiCompany/queueMutationFence.test.ts'])outputs.push({file:f,sha256:createHash('sha256').update(await readFile('/Users/manhtx/Documents/Macro Research Platform/'+f)).digest('hex')});console.log(JSON.stringify(outputs,null,2));await writeFile('/tmp/independent-queue-gate-edges-result.json',JSON.stringify(outputs,null,2));
