import{mkdtemp,readFile,writeFile,mkdir}from'node:fs/promises';import os from'node:os';import path from'node:path';import{createHash}from'node:crypto';import{RoleWorkQueue}from'../../../server/aiCompany/roleWorkQueue.ts';import{RoleEvidenceLedger}from'../../../server/aiCompany/roleEvidenceLedger.ts';import{evidenceProducingRoleWorkExecutor,modelRoleWorkExecutor}from'../../../server/aiCompany/roleWorkExecutor.ts';
const usage={input_tokens:0,output_tokens:0,estimated_cost_usd:0};const results:any[]=[];const sources=['server/aiCompany/roleWorkQueue.ts','server/aiCompany/roleWorkExecutor.ts','server/aiCompany/autonomousCoordinator.ts','server/aiCompany/roleEvidenceLedger.ts','server/aiCompany/nativeDispatchIssuance.test.ts','server/index.ts'];const hash=(x:any)=>createHash('sha256').update(x).digest('hex');async function hashes(){return Object.fromEntries(await Promise.all(sources.map(async f=>[f,hash(await readFile(f))])));}const before=await hashes();
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'independent-issuance-'));const ledger=new RoleEvidenceLedger(root),queue=new RoleWorkQueue(root,ledger);const item=await queue.create({project_id:'unit',backlog_id:'B',title:'Unit only no actual effect',role:'ux-research'});const claim=await queue.claim(item.work_id,'unit');return{root,ledger,queue,claim};}
for(const mode of ['concurrent','no-response-restart','missing-authority','wrong-authority','mutated-assignment','model-no-response','new-claim','provider-pending-input-mutation']){
 const f=await fixture();let calls=0;let capabilityLeaked=false;const adapter={id:'stub',complete:async(input:any)=>{calls++;if(mode==='provider-pending-input-mutation'){f.claim.role='functional-qa';f.claim.assignment!.namespace='changed-caller-snapshot';}capabilityLeaked ||=JSON.stringify(input).includes(f.claim.attempt_authority.token);if(mode==='no-response-restart'||mode==='model-no-response'||mode==='new-claim')return{ok:false,notes:'Injected no response; external effect unknown',evidence_ids:[],usage};return{ok:true,text:JSON.stringify({research_question:'unit',source_reference:input.task.role_execution.receipt_evidence_id,finding:'unit advisory only',confidence:0.2}),evidence_ids:[],usage};}};const execute=mode==='model-no-response'?modelRoleWorkExecutor(adapter,f.queue):evidenceProducingRoleWorkExecutor(adapter,f.ledger,f.queue);const outcomes:any[]=[];const capture=async(fn:any)=>{try{await fn();outcomes.push('fulfilled')}catch(e:any){outcomes.push(e.message)}};const file=path.join(f.root,'role-work-queue.jsonl');const initial=hash(await readFile(file));
 if(mode==='concurrent')await Promise.all([capture(()=>execute(f.claim,f.claim.attempt_authority)),capture(()=>execute(f.claim,f.claim.attempt_authority))]);
 else if(mode==='missing-authority')await capture(()=>execute(f.claim));
 else if(mode==='wrong-authority')await capture(()=>execute(f.claim,{...f.claim.attempt_authority,token:'0'.repeat(64)}));
 else if(mode==='mutated-assignment'){const selected=structuredClone(f.claim);selected.assignment!.scope=['changed intent'];await capture(()=>execute(selected,f.claim.attempt_authority));}
 else if(mode==='provider-pending-input-mutation')await capture(()=>execute(f.claim,f.claim.attempt_authority));
 else{
 await capture(()=>execute(f.claim,f.claim.attempt_authority));const restarted=new RoleWorkQueue(f.root,new RoleEvidenceLedger(f.root));const current=(await restarted.records())[0];const second=mode==='model-no-response'?modelRoleWorkExecutor(adapter,restarted):evidenceProducingRoleWorkExecutor(adapter,new RoleEvidenceLedger(f.root),restarted);await capture(()=>second(current,f.claim.attempt_authority));
 if(mode==='new-claim'){await restarted.blockAttempt(current.work_id,'explicit stop; prior effect unknown',f.claim.attempt_authority);await restarted.requeueBlocked(current.work_id);const next=await restarted.claim(current.work_id,'unit');await capture(()=>second(next,next.attempt_authority));}
 }
 const history=await readFile(file,'utf8');results.push({mode,root:f.root,stubCalls:calls,outcomes,receipts:(await f.ledger.records()).length,receiptMetadata:(await f.ledger.records()).map(row=>({role:row.role,namespace:row.namespace})),initialQueueHash:initial,finalQueueHash:hash(history),marker:(await f.queue.records())[0].provider_dispatch,capabilityLeaked,capabilityPersisted:history.includes(f.claim.attempt_authority.token)});
}
// Reservation committed but provenance fails: refuse dispatch, marker remains consumed.
{
const f=await fixture();await mkdir(path.join(f.root,'forensic-write-provenance.jsonl'));const saved=process.env.AI_COMPANY_FORENSIC_RUN_ID;process.env.AI_COMPANY_FORENSIC_RUN_ID='independent-unit';let calls=0;let error='';try{await evidenceProducingRoleWorkExecutor({id:'stub',complete:async()=>{calls++;throw new Error('must not run')}},f.ledger,f.queue)(f.claim,f.claim.attempt_authority);}catch(e:any){error=e.message;}finally{if(saved===undefined)delete process.env.AI_COMPANY_FORENSIC_RUN_ID;else process.env.AI_COMPANY_FORENSIC_RUN_ID=saved;}results.push({mode:'committed-provenance-failure',root:f.root,stubCalls:calls,error,marker:(await f.queue.records())[0].provider_dispatch});}
for(const invalid of [null,{},[],{attempt_id:'bad',provider_id:'stub',issued_at:new Date().toISOString()},{provider_id:'stub',attempt_id:'00000000-0000-0000-0000-000000000000',issued_at:'2026-10-04T00:00:00Z'}]){const f=await fixture();const file=path.join(f.root,'role-work-queue.jsonl');const rows=(await readFile(file,'utf8')).trim().split('\n').map(x=>JSON.parse(x));rows[0].provider_dispatch=invalid;const bytes=rows.map(x=>JSON.stringify(x)).join('\n')+'\n';await writeFile(file,bytes);let calls=0;let error='';try{await evidenceProducingRoleWorkExecutor({id:'stub',complete:async()=>{calls++;throw new Error('must not dispatch')}},f.ledger,f.queue)(f.claim,f.claim.attempt_authority);}catch(e:any){error=e.message;}results.push({mode:'malformed-historical-marker',root:f.root,invalid,error,stubCalls:calls,historyUnchanged:hash(bytes)===hash(await readFile(file))});}
const after=await hashes();const report={observedAt:new Date().toISOString(),sourceHashesBefore:before,sourceHashesAfter:after,sourceStable:JSON.stringify(before)===JSON.stringify(after),realProviderCalls:0,networkCalls:0,canonicalMutations:false,results};await writeFile('docs/successor-takeover/evidence/native-issuance-independent-result.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
