import { mkdtemp,writeFile } from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import{readFile}from'node:fs/promises';
import{RoleWorkQueue}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkQueue.ts';import{RoleEvidenceLedger}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleEvidenceLedger.ts';import{evidenceProducingRoleWorkExecutor}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkExecutor.ts';
const results=[];
for(const mode of ['concurrent','no-response']){
 const root=await mkdtemp(path.join(os.tmpdir(),'dispatch-issuance-before-'));const ledger=new RoleEvidenceLedger(root),queue=new RoleWorkQueue(root,ledger);const item=await queue.create({project_id:'unit',backlog_id:'UNIT',title:'Unit dispatch only; no product claim',role:'ux-research'});const claim=await queue.claim(item.work_id,'fixture');let calls=0;
 const execute=evidenceProducingRoleWorkExecutor({id:'stub',complete:async({task})=>{calls++;if(mode==='concurrent'){await new Promise(r=>setTimeout(r,20));return{ok:true,text:JSON.stringify({research_question:'Unit question',source_reference:task.role_execution!.receipt_evidence_id!,finding:'Unit advisory',confidence:0.2}),evidence_ids:[],usage:{input_tokens:1,output_tokens:1,estimated_cost_usd:0}};}return{ok:false,notes:'Injected provider no response',evidence_ids:[],usage:{input_tokens:0,output_tokens:0,estimated_cost_usd:0}};}},ledger,queue);
 let settled;if(mode==='concurrent')settled=await Promise.allSettled([execute(claim,claim.attempt_authority),execute(claim,claim.attempt_authority)]);else settled=[await execute(claim,claim.attempt_authority).then(()=>({status:'fulfilled'}),e=>({status:'rejected',reason:String(e)})),await execute(claim,claim.attempt_authority).then(()=>({status:'fulfilled'}),e=>({status:'rejected',reason:String(e)}))];
 results.push({mode,root,stubProviderCalls:calls,realProviderCalls:0,receipts:(await ledger.records()).length,outcomes:settled.map(x=>({status:x.status,...(x.status==='rejected'?{reason:String(x.reason)}:{})})),queueState:(await queue.records('unit'))[0].state});
}
const paths=['server/aiCompany/roleWorkQueue.ts','server/aiCompany/roleWorkExecutor.ts','server/aiCompany/roleEvidenceLedger.ts'];const hashes=Object.fromEntries(await Promise.all(paths.map(async p=>[p,createHash('sha256').update(await readFile(p)).digest('hex')])));const result={observedAt:new Date().toISOString(),hashes,results,networkCalls:0};await writeFile('/tmp/native-dispatch-issuance-after.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
