import {mkdtemp,writeFile}from'node:fs/promises';import os from'node:os';import path from'node:path';
import {RoleWorkQueue}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkQueue.ts';import {RoleEvidenceLedger}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleEvidenceLedger.ts';import{evidenceProducingRoleWorkExecutor}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkExecutor.ts';import{createConfiguredRoleModelAdapter}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/openaiCompatibleRoleAdapter.ts';
const root=await mkdtemp(path.join(os.tmpdir(),'native-packet-'));const ledger=new RoleEvidenceLedger(root),queue=new RoleWorkQueue(root,ledger);const template=await queue.create({project_id:'isolated',backlog_id:'TEMPLATE',title:'Unit template only',role:'ux-research'});
const assignment={...template.assignment!,assignment_id:'ASSIGNMENT:UNIT-PACKET',work_id:'UNIT-PACKET',objective_id:'REAL-CONTRACT-UNIT',objective:'Inspect exact original packet; no product outcome',namespace:'UNIT-NAMESPACE',run_id:'UNIT-RUN',risk_level:'P2' as const,scope:['only packet fixture'],allowed_paths:['docs/PRODUCT_GOAL.md'],forbidden_paths:[...template.assignment!.forbidden_paths,'private-unit-path'],acceptance_criteria:['preserve exact supplied acceptance'],timeout:17,retry_budget:0};
const [item]=await queue.createBatch([{work_id:'UNIT-PACKET',project_id:'isolated',backlog_id:'REAL-CONTRACT-UNIT',title:assignment.objective,role:'ux-research',assignment,namespace:assignment.namespace,run_id:assignment.run_id}]);const claim=await queue.claim(item.work_id,'fixture');let task:any,body:any;let calls=0;
const fetchImpl=async(_url:any,init:any)=>{calls++;body=JSON.parse(init.body);task=JSON.parse(body.messages[1].content);return new Response(JSON.stringify({choices:[{message:{content:'Unstructured unit prose, no research contract'}}],usage:{prompt_tokens:1,completion_tokens:1}}),{status:200});};
const adapter=createConfiguredRoleModelAdapter({MACRO_LLM_ENDPOINT:'https://unit.invalid/v1/chat/completions',MACRO_LLM_MODEL:'unit-stub',AI_COMPANY_ROLE_MAX_RETRIES:'3'},fetchImpl as any)!;
let error='';try{await evidenceProducingRoleWorkExecutor(adapter,ledger)(claim);}catch(e){error=e instanceof Error?e.message:String(e);}
const final=(await queue.records('isolated')).find(x=>x.work_id===item.work_id)!;
const report={root,stubFetchCalls:calls,realProviderCalls:0,canonicalAssignment:assignment,actualUserPacket:task,scopeDropped:!task.role_execution?.assignment,actualRisk:task.risk_level,actualCriteria:task.acceptance_criteria,actualBudget:task.budget,proseRejected:error,finalState:final.state,receiptStatus:(await ledger.records()).map(x=>x.protocol_status),capabilityLeaked:JSON.stringify(body).includes(claim.attempt_authority.token)};console.log(JSON.stringify(report,null,2));await writeFile('/tmp/native-provider-packet-after-result.json',JSON.stringify(report,null,2));
