import {mkdtemp,readFile,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {RoleWorkQueue} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkQueue.ts';import {RoleEvidenceLedger} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleEvidenceLedger.ts';import {mutateAdminRoleWorkQueue,assertAdminQueueRuntimeRoot} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/adminWorkQueueTransport.ts';
const digest=(x:any)=>createHash('sha256').update(x).digest('hex');const results:any[]=[];
for(const mode of ['old-handle','old-receipt-new-handle','current-receipt','missing-handle','erase-origin','malformed-attempt']){
const root=await mkdtemp(path.join(os.tmpdir(),'independent-admin-'+mode+'-'));const ledger=new RoleEvidenceLedger(root);const queue=new RoleWorkQueue(root,ledger);const item=await queue.create({project_id:'P',backlog_id:'B',title:'isolated only; no product effect',role:'ux-research',namespace:'N',run_id:'R'});const first:any=await mutateAdminRoleWorkQueue(queue,{action:'claim',work_id:item.work_id,owner:'first'});const record=(attempt:string)=>ledger.record({project_id:'P',work_id:item.work_id,role:item.role,namespace:'N',run_id:'R',attempt_id:attempt,provider_id:'stub',model:'stub',output:'same isolated bytes',limitation:'unit only',usage:{input_tokens:0,output_tokens:0,estimated_cost_usd:0}});let receipt=await record(first.item.attempt_id);await queue.blockAttempt(item.work_id,'stop',first.item.attempt_authority);await queue.requeueBlocked(item.work_id);const next:any=await mutateAdminRoleWorkQueue(queue,{action:'claim',work_id:item.work_id,owner:'next'});await mutateAdminRoleWorkQueue(queue,{action:'submit-review',work_id:item.work_id,attempt_authority:next.item.attempt_authority});
if(mode==='current-receipt')receipt=await record(next.item.attempt_id);if(mode==='erase-origin'){const{evidence_kind,...rest}=receipt as any;await writeFile(path.join(root,'role-evidence.jsonl'),JSON.stringify({...rest,evidence_kind:'INDEPENDENT_INPUT'})+'\n');}if(mode==='malformed-attempt')await writeFile(path.join(root,'role-evidence.jsonl'),JSON.stringify({...receipt,attempt_id:'bad'})+'\n');
const file=path.join(root,'role-work-queue.jsonl');const before=digest(await readFile(file));let result='';try{const response:any=await mutateAdminRoleWorkQueue(queue,{action:'complete',work_id:item.work_id,evidence_ids:[receipt.evidence_id],research_result:{research_question:'fixture',source_reference:receipt.evidence_id,finding:'unit only',confidence:.5},attempt_authority:mode==='missing-handle'?undefined:mode==='old-handle'?first.item.attempt_authority:next.item.attempt_authority});result=response.item.state;}catch(e:any){result=e.message;}const history=await readFile(file,'utf8');results.push({mode,root,result,before,after:digest(history),handleTokenPersisted:history.includes(first.item.attempt_authority.token)||history.includes(next.item.attempt_authority.token)});
}
for(const [queueRoot,stateRoot]of [['/tmp/control/projects/macro-os','/tmp/control'],['/tmp/wrong/projects/macro-os','/tmp/control']]){let result='ACCEPT';try{assertAdminQueueRuntimeRoot(queueRoot,stateRoot);}catch(e:any){result=e.message;}results.push({mode:'root-guard',queueRoot,stateRoot,result});}
const repo='/Users/manhtx/Documents/Macro Research Platform';const hashes:any={};for(const f of ['server/aiCompany/roleEvidenceLedger.ts','server/aiCompany/roleWorkQueue.ts','server/aiCompany/roleWorkExecutor.ts','server/aiCompany/evidenceResolver.ts','server/aiCompany/adminWorkQueueTransport.ts','server/aiCompany/adminWorkQueueTransport.test.ts','server/index.ts'])hashes[f]=digest(await readFile(path.join(repo,f)));const report={providerCalls:0,canonicalMutations:false,routeVerified:'source inspection only; server/index not imported',hashes,results};await writeFile('/tmp/native-admin-independent-review-result.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
