import {mkdtemp,readFile,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {RoleWorkQueue} from '../../../server/aiCompany/roleWorkQueue.ts';import {RoleEvidenceLedger} from '../../../server/aiCompany/roleEvidenceLedger.ts';import {evidenceProducingRoleWorkExecutor} from '../../../server/aiCompany/roleWorkExecutor.ts';import {createConfiguredRoleModelAdapter} from '../../../server/aiCompany/openaiCompatibleRoleAdapter.ts';
const usage={input_tokens:1,output_tokens:1,estimated_cost_usd:0};const results:any[]=[];const hashes:any={};const sources=['roleWorkExecutor.ts','openaiCompatibleRoleAdapter.ts','roleEvidenceLedger.ts','orchestrator.ts','researchResult.ts','roleWorkQueue.ts','nativeProviderContract.test.ts'];for(const f of sources)hashes[f]=createHash('sha256').update(await readFile('server/aiCompany/'+f)).digest('hex');
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'native-independent-contract-'));const ledger=new RoleEvidenceLedger(root);const queue=new RoleWorkQueue(root,ledger);const template=await queue.create({project_id:'unit',backlog_id:'template',title:'unit only',role:'ux-research'});const assignment={...template.assignment!,work_id:'UNIT',assignment_id:'A-UNIT',risk_level:'P2' as const,timeout:0.05,token_budget:33,retry_budget:1,scope:['exact fixture'],allowed_paths:['allowed'],forbidden_paths:['private'],acceptance_criteria:['exact unit criterion'],run_id:'R',namespace:'N'};const[item]=await queue.createBatch([{work_id:'UNIT',project_id:'unit',backlog_id:'B',title:'unit only',role:'ux-research',assignment,run_id:'R',namespace:'N'}]);const claim=await queue.claim(item.work_id,'fixture');return{root,ledger,queue,claim,assignment};}
const env={MACRO_LLM_ENDPOINT:'https://unit.invalid/v1/chat/completions',MACRO_LLM_MODEL:'stub',AI_COMPANY_ROLE_MAX_RETRIES:'3',AI_COMPANY_ROLE_MAX_TOKENS:'1000'};
{
const f=await fixture();let wire:any;let calls=0;const adapter=createConfiguredRoleModelAdapter(env,(async(_url:any,init:any)=>{calls++;wire=JSON.parse(init.body);const packet=JSON.parse(wire.messages[1].content);return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({research_question:'actual question',source_reference:packet.role_execution.receipt_evidence_id,finding:'actual supplied finding; only unit transcript',confidence:0.19})}}],usage:{prompt_tokens:1,completion_tokens:1}}),{status:200});}) as any)!;const output=await evidenceProducingRoleWorkExecutor(adapter,f.ledger)(f.claim);await f.queue.submitForReview('UNIT',f.claim.attempt_authority);const admitted=await f.queue.complete('UNIT',output.evidence_ids,output.research_result,undefined,undefined,undefined,undefined,f.claim.attempt_authority);const packet=JSON.parse(wire.messages[1].content);results.push({case:'wire-and-typed-research',root:f.root,assignmentExact:JSON.stringify(packet.role_execution.assignment)===JSON.stringify(f.assignment),rawCapabilityLeaked:JSON.stringify(wire).includes(f.claim.attempt_authority.token),packet,outputTokenCeiling:wire.max_tokens,requestCount:calls,result:output.research_result,terminal:admitted.state});
}
{
const f=await fixture();const execute=evidenceProducingRoleWorkExecutor({id:'stub',complete:async()=>({ok:true,text:'No typed research fields',evidence_ids:[],usage})},f.ledger);let error;try{await execute(f.claim)}catch(e:any){error=e.message;}results.push({case:'prose-rejection',root:f.root,error,queueState:(await f.queue.records()).find(x=>x.work_id==='UNIT')?.state});
}
{
const f=await fixture();let calls=0;const execute=evidenceProducingRoleWorkExecutor({id:'stub',complete:async({task})=>{calls++;return{ok:true,text:JSON.stringify({research_question:'unit',source_reference:task.role_execution!.receipt_evidence_id,finding:'unit'+calls,confidence:0.2}),evidence_ids:[],usage};}},f.ledger);await execute(f.claim);let error;try{await execute(f.claim)}catch(e:any){error=e.message;}results.push({case:'sequential-same-claim-replay',root:f.root,requestCount:calls,error,receiptCount:(await f.ledger.records()).length});
}
{
let calls=0;const adapter=createConfiguredRoleModelAdapter(env,(async(_url:any,init:any)=>{calls++;return await new Promise((_resolve,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('unit aborted')),{once:true}));}) as any)!;const start=Date.now();const response=await adapter.complete({worker_id:'coder',task:{task_id:'TIME',project_id:'unit',risk_level:'P1',acceptance_criteria:['unit'],budget:{max_attempts:2,timeout_seconds:0.05}}});results.push({case:'deadline',requestCount:calls,elapsedMs:Date.now()-start,ok:response.ok,notes:response.notes});
}
const hashesAfter:any={};for(const f of sources)hashesAfter[f]=createHash('sha256').update(await readFile('server/aiCompany/'+f)).digest('hex');const report={generatedAt:new Date().toISOString(),realProviderCalls:0,networkCalls:0,canonicalMutations:false,hashes,hashesAfter,sourceStable:JSON.stringify(hashes)===JSON.stringify(hashesAfter),results};await writeFile('docs/successor-takeover/evidence/native-contract-independent-result.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
