import {evaluatePromotion} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/releasePromotion.ts';
import {preReleaseReviewRoles} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/preReleaseReviewGate.ts';
import {evaluateCadenceQuorum} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/cadenceQuorum.ts';
import {cadencePolicyFor} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/operatingCadence.ts';
import {isSuccessfulRoleWork} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkQueue.ts';
import {writeFile,readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
const row=(id,role,backlog)=>({work_id:id,project_id:'unit',backlog_id:backlog,title:'In-memory negative control only',role,state:'DONE',depends_on:['WITHDRAWN'],evidence_ids:['UNIT'],created_at:'2026-10-01T00:00:00.000Z',updated_at:'2026-10-01T00:00:00.000Z',...(['functional-qa','quality-control'].includes(role)?{review_verdict:{verdict:'PASS',gate:'unit',summary:'Unit only',evidence:['UNIT'],failure_class:'NONE',root_cause:'Unit only',recovery_required:false,recovery_actions:[],unblock_evidence:[],retry_budget:0,next_review_trigger:'unit',confidence:.2}}:{})});
const source={...row('WITHDRAWN','ux-research','SOURCE'),state:'QUARANTINED',depends_on:[]};const releaseRows=[source,...preReleaseReviewRoles.map(r=>row(r,r,'UNIT'))];const governance=[source,...cadencePolicyFor('daily').accountable_roles.map(r=>row(r,r,'CADENCE:daily:unit'))];
const report={observedAt:new Date().toISOString(),scope:'In-memory fault snapshots only; no canonical company work or product evidence',promotion:evaluatePromotion(releaseRows as never,'UNIT'),currentReleaseSuccess:releaseRows.slice(1).map(r=>({role:r.role,success:isSuccessfulRoleWork(r as never,releaseRows as never)})),cadence:evaluateCadenceQuorum({cadence:'daily',work:governance as never}),currentGovernanceSuccess:governance.slice(1).map(r=>({role:r.role,success:isSuccessfulRoleWork(r as never,governance as never)})),sourceHashes:Object.fromEntries(await Promise.all(['preReleaseReviewGate.ts','releasePromotion.ts','cadenceQuorum.ts','roleWorkQueue.ts'].map(async name=>[name,createHash('sha256').update(await readFile('/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/'+name)).digest('hex')]))),realProviderCalls:0,networkCalls:0};console.log(JSON.stringify(report,null,2));await writeFile('/tmp/raw-terminal-consumer-after.json',JSON.stringify(report,null,2));
