import {evaluatePromotion} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/releasePromotion.ts';
import {preReleaseReviewRoles} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/preReleaseReviewGate.ts';
import {evaluateCadenceQuorum} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/cadenceQuorum.ts';
import {cadencePolicyFor} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/operatingCadence.ts';
import {isSuccessfulRoleWork} from '/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkQueue.ts';
import {writeFile,readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
const row=(id,role,backlog)=>({work_id:id,project_id:'unit',backlog_id:backlog,title:'In-memory negative control only',role,state:'DONE',depends_on:['WITHDRAWN'],evidence_ids:['UNIT'],created_at:'2026-10-01T00:00:00.000Z',updated_at:'2026-10-01T00:00:00.000Z',...(['functional-qa','quality-control'].includes(role)?{review_verdict:{verdict:'PASS',gate:'unit',summary:'Unit only',evidence:['UNIT'],failure_class:'NONE',root_cause:'Unit only',recovery_required:false,recovery_actions:[],unblock_evidence:[],retry_budget:0,next_review_trigger:'unit',confidence:.2}}:{})});
const source={...row('WITHDRAWN','ux-research','SOURCE'),state:'QUARANTINED',depends_on:[]};const releaseRows=[source,...preReleaseReviewRoles.map(r=>row(r,r,'UNIT'))];const governance=[source,...cadencePolicyFor('daily').accountable_roles.map(r=>row(r,r,'CADENCE:daily:unit'))];

import{mkdtemp}from'node:fs/promises';import os from'node:os';import path from'node:path';import{RoleWorkQueue}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkQueue.ts';import{RoleEvidenceLedger}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleEvidenceLedger.ts';import{ResearchSignalLedger}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/researchSignalLedger.ts';import{synthesizeCompletedResearch}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/researchSynthesis.ts';
const cases:any[]=[];for(const kind of ['withdrawn','healthy','missing','invalid-pass','hold','missing-pass']){const base=kind==='missing'?[]:[{...source,state:kind==='withdrawn'?'QUARANTINED':'DONE'}];const release=[...base,...releaseRows.slice(1).map(r=>({...r}))];if(kind==='invalid-pass')release.find(r=>r.role==='functional-qa')!.review_verdict={verdict:'PASS'} as never;if(kind==='hold')release.find(r=>r.role==='functional-qa')!.review_verdict!.verdict='HOLD';if(kind==='missing-pass')delete release.find(r=>r.role==='functional-qa')!.review_verdict;const gov=[...base,...governance.slice(1)];cases.push({kind,promotion:evaluatePromotion(release as never,'UNIT'),cadence:evaluateCadenceQuorum({cadence:'daily',work:gov as never})});}
const root=await mkdtemp(path.join(os.tmpdir(),'raw-independent-')),evidence=new RoleEvidenceLedger(root),queue=new RoleWorkQueue(root,evidence);const usage={input_tokens:0,output_tokens:0,estimated_cost_usd:0};async function finish(work_id:string){const c=await queue.claim(work_id,'unit'),e=await evidence.record({project_id:'unit',work_id,attempt_id:c.attempt_id!,role:'ux-research',namespace:c.assignment!.namespace,run_id:c.assignment!.run_id,provider_id:'stub',model:'stub',output:'Unit advisory only',limitation:'No product evidence',usage});await queue.submitForReview(work_id,c.attempt_authority);return queue.complete(work_id,[e.evidence_id],{research_question:'Unit',source_reference:e.evidence_id,finding:'Unit only',confidence:.2},undefined,undefined,undefined,undefined,c.attempt_authority);}
const a=await queue.create({project_id:'unit',backlog_id:'A',title:'Unit source',role:'ux-research'});await finish(a.work_id);const b=await queue.create({project_id:'unit',backlog_id:'B',title:'Unit dependent',role:'ux-research',depends_on:[a.work_id]});await finish(b.work_id);const healthyLedger=new ResearchSignalLedger(await mkdtemp(path.join(os.tmpdir(),'raw-independent-healthy-')));const healthySignals=await synthesizeCompletedResearch({projectId:'unit',items:await queue.records(),ledger:healthyLedger});await queue.quarantine(a.work_id,'Unit withdrawal');const invalidLedger=new ResearchSignalLedger(await mkdtemp(path.join(os.tmpdir(),'raw-independent-withdraw-')));const withdrawnSignals=await synthesizeCompletedResearch({projectId:'unit',items:await queue.records(),ledger:invalidLedger});const missingLedger=new ResearchSignalLedger(await mkdtemp(path.join(os.tmpdir(),'raw-independent-missing-')));const missingSignals=await synthesizeCompletedResearch({projectId:'unit',items:(await queue.records()).filter(x=>x.work_id!==a.work_id),ledger:missingLedger});
const files=['preReleaseReviewGate.ts','cadenceQuorum.ts','researchSynthesis.ts','releasePromotion.ts','roleWorkQueue.ts','preReleaseReviewGate.test.ts','cadenceQuorum.test.ts','researchSynthesis.test.ts','releasePromotion.test.ts','runtime.ts','runtime.test.ts'];const hashes=Object.fromEntries(await Promise.all(files.map(async p=>[p,createHash('sha256').update(await readFile('/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/'+p)).digest('hex')])));const report={observedAt:new Date().toISOString(),cases,synthesis:{healthySignals,withdrawnSignals,missingSignals,withdrawnStoredSignals:await invalidLedger.records('unit'),historicalLeafState:(await queue.records()).find(x=>x.work_id===b.work_id)!.state},hashes,realProviderCalls:0,networkCalls:0};console.log(JSON.stringify(report,null,2));await writeFile('/tmp/raw-terminal-consumer-independent-results.json',JSON.stringify(report,null,2));
