import{mkdtemp,mkdir,writeFile,readFile,access}from'node:fs/promises';import os from'node:os';import path from'node:path';import{spawn}from'node:child_process';import{createRequire}from'node:module';import{createHash}from'node:crypto';
import{RoleWorkQueue,isSuccessfulRoleWork}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkQueue.ts';import{RoleEvidenceLedger}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleEvidenceLedger.ts';import{RoleHandoffLedger}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleHandoffLedger.ts';import{evidenceProducingRoleWorkExecutor}from'/Users/manhtx/Documents/Macro Research Platform/server/aiCompany/roleWorkExecutor.ts';
const repo='/Users/manhtx/Documents/Macro Research Platform',usage={input_tokens:0,output_tokens:0,estimated_cost_usd:0},research=(id:string)=>({research_question:'Unit only',source_reference:id,finding:'Advisory fixture only; outcome UNKNOWN',confidence:.2});
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'dependency-independent-')),runtime=path.join(root,'.ai-company/runtime/projects/isolated'),ledger=new RoleEvidenceLedger(runtime),queue=new RoleWorkQueue(runtime,ledger);const source=await queue.create({project_id:'isolated',backlog_id:'B',title:'Unit source',role:'ux-research',namespace:'N',run_id:'R'});const c=await queue.claim(source.work_id,'unit-source'),e=await ledger.record({project_id:'isolated',work_id:source.work_id,attempt_id:c.attempt_id!,role:'ux-research',namespace:'N',run_id:'R',provider_id:'stub',model:'stub',output:'Unit only',limitation:'No product outcome',usage});await queue.submitForReview(source.work_id,c.attempt_authority);await queue.complete(source.work_id,[e.evidence_id],research(e.evidence_id),undefined,undefined,undefined,undefined,c.attempt_authority);const consumer=await queue.create({project_id:'isolated',backlog_id:'B',title:'Unit consumer',role:'ux-research',namespace:'N',run_id:'R',depends_on:[source.work_id]});const withdraw=async()=>await queue.quarantine(source.work_id,'Independent unit withdrawal',(await queue.records()).find(x=>x.work_id===source.work_id)!);return{root,runtime,ledger,queue,source,consumer,withdraw};}

const f=await fixture();
const b=await f.queue.claim(f.consumer.work_id,'unit');const eb=await f.ledger.record({project_id:'isolated',work_id:b.work_id,attempt_id:b.attempt_id!,role:'ux-research',namespace:'N',run_id:'R',provider_id:'stub',model:'stub',output:'Unit middle source',limitation:'Unit only',usage});await f.queue.submitForReview(b.work_id,b.attempt_authority);await f.queue.complete(b.work_id,[eb.evidence_id],research(eb.evidence_id),undefined,undefined,undefined,undefined,b.attempt_authority);
const c=await f.queue.create({project_id:'isolated',backlog_id:'B',title:'Transitive CAS unit',role:'ux-research',namespace:'N',run_id:'R',depends_on:[b.work_id]});const cc=await f.queue.claim(c.work_id,'unit');const ec=await f.ledger.record({project_id:'isolated',work_id:c.work_id,attempt_id:cc.attempt_id!,role:'ux-research',namespace:'N',run_id:'R',provider_id:'stub',model:'stub',output:'Unit leaf',limitation:'Unit only',usage});await f.queue.submitForReview(c.work_id,cc.attempt_authority);
let release!:()=>void,entered!:()=>void;const pause=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>entered=r);const q=new RoleWorkQueue(f.runtime,{resolve:async id=>{entered();await pause;return f.ledger.resolve(id);}});const pending=q.complete(c.work_id,[ec.evidence_id],research(ec.evidence_id),undefined,undefined,undefined,undefined,cc.attempt_authority);await ready;await f.withdraw();const before=await readFile(path.join(f.runtime,'role-work-queue.jsonl'));release();let state='',error='';try{state=(await pending).state;}catch(e){error=String(e);}const rows=await f.queue.records();const files=['server/aiCompany/roleWorkQueue.ts','server/aiCompany/recursiveDependencyAuthority.test.ts'];const hashes=Object.fromEntries(await Promise.all(files.map(async p=>[p,createHash('sha256').update(await readFile(path.join(repo,p))).digest('hex')])));const report={observedAt:new Date().toISOString(),root:f.root,hashes,state,error,sourceState:rows.find(x=>x.work_id===f.source.work_id)!.state,middleState:rows.find(x=>x.work_id===b.work_id)!.state,leafState:rows.find(x=>x.work_id===c.work_id)!.state,bytesUnchanged:before.equals(await readFile(path.join(f.runtime,'role-work-queue.jsonl'))),currentLeafSuccess:isSuccessfulRoleWork(rows.find(x=>x.work_id===c.work_id)!,rows),realProviderCalls:0,networkCalls:0};console.log(JSON.stringify(report,null,2));await writeFile('/tmp/recursive-dependency-independent-transitive-cas-after.json',JSON.stringify(report,null,2));
