import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

describe('local role dispatcher contract', () => {
  it('supports both local AI runners and requires a role completion marker', async () => {
    const source = await readFile(new URL('./ai-company-role-dispatch.mjs', import.meta.url), 'utf8');
    expect(source).toContain("runner !== 'codex'");
    expect(source).toContain("process.env.RUNNER || 'codex'");
    expect(source).toContain("process.env.AI_COMPANY_MODEL || 'gpt-5.6-sol'");
    expect(source).toContain('ROLE_WORK_COMPLETE');
    expect(source).toContain('ROLE_WORK_BLOCKED');
    expect(source).toContain('handoff ledger');
    expect(source).toContain('Coordinator handoff is missing');
    expect(source).toContain('Dependency is not complete');
    expect(source).toContain('finalMarker');
    expect(source).toContain('await queue.claim(workId');
    expect(source).toContain('await queue.complete(workId');
    expect(source).toContain('role-dispatch-evidence.jsonl');
    expect(source).toContain('AI_COMPANY_CODEX_SANDBOX');
    expect(source).toContain('C13 BOUNDED GUARD OVERRIDE');
    expect(source).toContain("'--ephemeral'");
    expect(source).toContain("'--ignore-user-config'");
    expect(source).toContain('AI_COMPANY_CODEX_HOME');
    expect(source).toContain('terminalOutputSeen');
    expect(source).toContain('terminalOutputBuffer');
    expect(source).toContain('CEO_GUILD_DECISION_JSON');
    expect(source).toContain('CeoGuildDecisionLedger');
    expect(source).toContain('TECHNICAL_PLAN_JSON');
    expect(source).toContain('CRITIQUE_JSON');
    expect(source).toContain('PM STRUCTURED OUTPUT');
    expect(source).toContain('METRIC_CONTRACT_JSON');
    expect(source).toContain('metric contract invalid');
    expect(source).toContain('TECH LEAD STRUCTURED OUTPUT');
    expect(source).toContain('ENGINEERING STRUCTURED OUTPUT');
    expect(source).toContain('CEO STRUCTURED OUTPUT');
    expect(source).toContain('structured role output invalid');
    expect(source).toContain('AI_COMPANY_VITEST_CACHE_DIR');
    expect(source).toContain('missingRecoveryFields');
    expect(source).toContain('REVIEW_VERDICT_JSON');
    expect(source).toContain('final assistant message MUST include this exact marker line');
    expect(source).toContain('sourceWorkId, attempts');
    expect(source).toContain('knownWorkIds.has(decision.subject_id)');
    expect(source).toContain('accountableRole');
    expect(source).toContain('terminalMarkerPresent');
    expect(source).toContain('fallbackArtifactOutput');
    expect(source).toContain('fallbackArtifactPath');
    expect(source).toContain('bounded read-after-write retry');
    expect(source).toContain('--output-last-message');
    expect(source).toContain('Any ROLE_WORK_COMPLETE or other terminal marker inside a dependency is historical input');
    expect(source).toContain('bounded deterministic review fallback');
    expect(source).toContain('hasKnownMetricDefect');
    expect(source).toContain('exitCode !== 0 && !terminalMarkerPresent');
    expect(source).toContain("['READY', 'CLAIMED', 'IN_REVIEW', 'DONE', 'BLOCKED'].includes(postRunWork.state)");
    expect(source).toContain('INSPECTION BUDGET');
    expect(source).toContain('const cycleId = work.assignment.cycle_id || work.assignment.run_id');
    expect(source).toContain('epoch_id: epochId');
    expect(source).toContain('cycle_id: cycleId');
    expect(source).toContain('Worker pre-committed DONE');
    expect(source).toContain("postRunWork.state === 'DONE'");
    expect(source).toContain('worker pre-committed DONE before dispatcher evidence and contract validation');
    expect(source).toContain('Provider-facing evidence citations may be paths or command references');
    expect(source).toContain('Reviewers must validate dependency evidence');
  });
});
